In [75]:
# set up
import numpy as np
from numpy import linalg as LA

# Zadanie 1.

### 1.1 
Utwórz zestaw danych X składający się z 1000 wektorów dwuwymiarowych xi = (x1i,x2i).T, </br>
dla i = 1, 2, …, 1000, wygenerowanych losowo przy użyciu dwuwymiarowego </br>
rozkładu normalnego o średniej [3, 5] i macierzy kowariancji [12, 3; 3, 1]. </br>

In [47]:
mu = [3, 5]
sigma = [[12, 3], 
         [3, 1]]

X = np.random.multivariate_normal(mu, sigma, 1000)

### 1.2
Ustandaryzuj dane, tak aby średnia dla każdego z wymiarów wynosiła 0, a wariancja 1.

In [48]:
X_std = (X - X.mean(axis=0)) / X.std(axis=0)

In [49]:
X_std.std(axis=0), X_std.mean(axis=0)

(array([1., 1.]), array([-7.90825738e-16, -1.81654691e-15]))

### 1.2
c) Policz macierz kowariancji S ustandaryzowanego zestawu danych X_std

In [82]:
print(np.cov(X.T))
print()
sigma_std = np.cov(X_std.T)
print(sigma_std)

[[12.69215901  3.27895354]
 [ 3.27895354  1.11765077]]

[[1.001001   0.87146302]
 [0.87146302 1.001001  ]]


In [66]:
def COV(X, Y):
    return np.sum((X - X.mean()) * (Y - Y.mean())) / len(X)

In [72]:
COV_X_Y = COV(X_std[:, 0], X_std[:, 1])
COV_X_X = COV(X_std[:, 0], X_std[:, 0])
COV_Y_Y = COV(X_std[:, 1], X_std[:, 1])
print('X_std matrix:')
print(COV_X_Y)
print(COV_X_X)
print(COV_Y_Y)

X_std matrix:
0.8705915534368085
1.0000000000000002
1.0000000000000002


In [71]:
print('X matrix:')
print(COV(X[:, 0], X[:, 1]))
print(COV(X[:, 0], X[:, 0]))
print(COV(X[:, 1], X[:, 1]))

X matrix:
3.2756745816121002
12.67946684762321
1.116533120470153


### 1.3
Wyznacz wartości własne λ1 i λ2 oraz odpowiadające im wektory własne v1 i v2 <br>
macierzy kowariancji S. Dla ustalenia notacji, wartości własne porządkujemy malejąco, <br>
tzn. λ1 > λ2. <br>
<br>
\begin{equation*} Det\begin{pmatrix}cov(X, X)-\lambda&cov(X, Y)\\cov(X, Y)&cov(Y, Y)-\lambda\end{pmatrix}=0. \end{equation*}
<br>
\begin{equation*} \begin{bmatrix}cov(X, X)&cov(X, Y)\\cov(X, Y)&cov(Y, Y)\end{bmatrix} \begin{bmatrix}x_{11}\\x_{12}\end{bmatrix} = -\lambda \begin{bmatrix}x_{11}\\x_{12}\end{bmatrix}\end{equation*}

In [102]:
# calculate eigenvalues
delta = (COV_X_X + COV_Y_Y) ** 2 - 4 * (COV_X_X * COV_Y_Y - COV_X_Y * COV_X_Y)
lambda_1 = ((COV_X_X + COV_Y_Y) - np.sqrt(delta)) / 2
lambda_2 = ((COV_X_X + COV_Y_Y) + np.sqrt(delta)) / 2

print(f'λ1: {lambda_1}, λ2: {lambda_2}')

λ1: 0.12940844656319173, λ2: 1.8705915534368087


In [104]:
# calculate eigenvectors
(COV_X_X + lambda_1) * (COV_Y_Y + lambda_1) - COV_X_Y ** 2

0.517633786252767

In [101]:
v, w = LA.eig(sigma_std)
print(f'Eigenvectors:\n{w},\n\nEigenvalues: {v}')

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]],

Eigenvalues: [1.87246402 0.12953798]
