In [2]:
# Set up
import numpy as np
import math
from scipy.special import factorial

Zadanie 0. <br/>
Utwórz skrypt definiujący poniższe zmienne: <br/>
a = [1, 2, 3, 4, …, 100] (wektor złożony z liczb całkowitych od 1 do 100) <br/>
b = [1, 3, 5, 7, …, 99] (wektor złożony z liczb całkowitych nieparzystych od 1 do 99) <br/>
c = [-1.00 * π, -0.99 * π, …, -0.01 * π, 0, 0.01 * π, …, 0.99 * π, 1.00 * π] <br/>
d = [-1.00 * π, -0.99 * π, …, -0.01 * π, 0.01 * π, …, 0.99 * π, 1.00 * π] <br/>
e = [e1, e2, …, e100], gdzie ei = sin(i), jeśli sin(i) > 0, lub ei = 0 w przeciwnym przypadku <br/>

In [2]:
a = np.arange(1, 101)
b = np.arange(50) * 2 + 1
c = np.linspace(-math.pi, math.pi,201).round(6)
d = c[c.nonzero()]
e = np.maximum(np.zeros(100), np.sin((np.arange(100) + 1))) 
# Alternative e
# e = [max(0, math.sin(x)) for x in range(1,101)]

#a,b,c,d,e

A = macierz rozmiaru 10 x 10 zawierająca liczby całkowite od 1 do 100: w pierwszym wierszu od
lewej 1, 2, …, w drugim wierszu od lewej 11, 12, .., itd. (wskazówka: użyć polecenia reshape)

In [74]:
A = np.arange(1, 101).reshape(10,10)
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

B = macierz trójdiagonalna rozmiaru 100 x 100 mająca na głównej przekątnej liczby całkowite od 1
do 100, a poniżej i powyżej głównej przekątnej liczby od 99 do 1

In [66]:
B = np.diag(np.arange(1, 101)) + np.diag(np.arange(99, 0, -1), k=1) + np.diag(np.arange(99, 0, -1), k=-1)
B

array([[  1,  99,   0, ...,   0,   0,   0],
       [ 99,   2,  98, ...,   0,   0,   0],
       [  0,  98,   3, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,  98,   2,   0],
       [  0,   0,   0, ...,   2,  99,   1],
       [  0,   0,   0, ...,   0,   1, 100]])

C = macierz trójkątna górna wypełniona jedynkami (łącznie z główną przekątną)

In [70]:
C = np.triu(np.ones((10,10)))
C

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

D = macierz rozmiaru 2 x 100, w której pierwszy wiersz zawiera elementy d1i = 1 + 2 + … + i, a
drugi wiersz zawiera elementy d2i = i!

In [3]:
D1 = np.cumsum(np.arange(1,101))
D2 = np.cumprod(np.arange(1,101), dtype=np.float)
D = np.append(D1,D2).reshape(2,100)

E = macierz rozmiaru 100 x 100 mająca 1 w pozycji (i, j), jeśli i dzieli j, lub 0 w przeciwnym
przypadku. 

In [5]:
E = np.array([[0 if i % j else 1 for j in range(1, 101)] for i in range(1, 101)])
